window.TUKKI={
ar:{
 dir:'rtl',switchTo:'English',nav:['كيف نعمل','لماذا تُكِّي','الأسعار','أسئلة'],navCta:'احجز مكالمة',
 eyebrow:'شريكك في النمو',hero:['سـوّق بثقة.','انمُ بوضـوح.','ابقَ في الذاكـرة.'],
 heroBody:'نساعد الأعمال في العراق على النمو بتسويق واضح وتدريب عملي، بالعربية. ثلاث خطوات فقط: مكالمة مجانية لمناقشة مشروعك واحتياجاتك، ثم توصيات واضحة، ثم التنفيذ معك.',
 stats:[['50+','عملاً'],['14+','سنة من الخبرة'],['3','خطوات قصيرة']],
 cta1:'احجز مكالمة عبر واتساب',cta2:'كيف نعمل',
 howEyebrow:'كيف نعمل',howTitle:'ثلاث خطوات قصيرة.',
 steps:[['مكالمة مجانية لمناقشة مشروعك','نتعرّف على عملك وما تريد تحقيقه. بلا أي التزام.'],['توصيات واضحة','نخبرك بما يجب فعله أولاً، ولماذا، وكم سيكلّف.'],['التنفيذ','ننفّذ معك وندرّب فريقك، ثم نقيس ما الذي تغيّر.']],
 whyEyebrow:'لماذا تُكِّي',whyTitle:'تدريب يُفهم هنا، ويُطبَّق هنا.',
 benefits:[['بالعربية أولاً','المحتوى والأمثلة والأدوات كلها بالعربية.'],['من واقع السوق','أمثلة من القنوات والعادات التي يستخدمها الناس في العراق فعلاً.'],['عملي لا نظري','كل جلسة تنتهي بخطوة تطبّقها في الأسبوع نفسه.'],['لفريقك كله','من صاحب العمل إلى من يدير الصفحات ويرد على الرسائل.'],['أدوات تبقى معك','قوالب وأوراق عمل تستخدمها بعد انتهاء التدريب.'],['نتائج تُقاس','نتفق على ما سنقيسه قبل أن نبدأ.']],
 priceEyebrow:'الأسعار',priceTitle:'كم يكلّف؟',priceBody:'نحدد السعر حسب حجم المشروع أو الخدمة وما تحتاجه. هذا دليل لتعرف ما تتوقعه.',
 prices:[['مكالمة لمناقشة مشروعك','مجاناً','نتعرّف على عملك ونرى إن كان تُكِّي مناسباً لك.'],['ورشة عمل','من 800,000 د.ع','يوم تدريبي واحد حول موضوع محدد.'],['برنامج تُكِّي','من 3,250,000 د.ع','ستة أسابيع من الجلسات والمتابعة التي تلبّي الاحتياجات المباشرة، مع أدوات وقوالب لفريقك.'],['متابعة مستمرة','حسب الاتفاق','دعم شهري لفريقك بعد البرنامج. نتفق على النطاق والسعر قبل البدء.']],
 programEyebrow:'برنامج تُكِّي',programTitle:'ماذا يشمل البرنامج؟',programBody:'نبني البرنامج حول ما يحتاجه مشروعك. هذه الخدمات التي يمكن أن يشملها.',programBack:'العودة إلى الأسعار',
 program:[['البحث','نفهم السوق والعملاء والفرص قبل أي خطوة.'],['دراسة المنافسين','ما يفعله المنافسون، وأين المساحة المتاحة لك.'],['تحليل SEO وGEO وAEO','كيف يظهر عملك في محركات البحث وأدوات الذكاء الاصطناعي ومحركات الإجابة.'],['توليد الأفكار','أفكار واضحة مبنية على البحث، لا على التخمين.'],['خارطة طريق لـ 90 يوماً','خطة عملية بأولويات ومواعيد واضحة.'],['الهوية البصرية','هوية تعبّر عن عملك وتبقى في الذاكرة.'],['نظام تصميم للرقمي والمطبوع','قواعد وقوالب تحافظ على اتساق كل ما تنشره.'],['إدارة وسائل التواصل الاجتماعي','محتوى ونشر وتفاعل بشكل منتظم.'],['الإعلانات المدفوعة','حملات مدروسة تصل إلى الجمهور الصحيح.'],['دعم متعدد المنصات','حضور متناسق عبر كل القنوات التي يستخدمها عملاؤك.'],['المواقع الإلكترونية','مواقع سريعة وواضحة تحوّل الزوار إلى عملاء.'],['التطبيقات','تطبيقات تخدم عملك وعملاءك.'],['أنظمة إدارة العملاء (CRM)','أنظمة تنظّم بيانات العملاء والمتابعة والمبيعات.'],['التقارير والتوصيات','أرقام واضحة وخطوات تالية مبنية عليها.']],
 priceNote:'الجلسة الأولى بدون أي التزام.',
 quoteTitle:'كلمة من عميل',quote:'استفدنا كثيراً من وجود شخص من خارج المؤسسة يشاركنا أدوات وأنظمة وفرصاً غيّرت طريقة عملنا.',quoteBy:'تفاصيل العميل محجوبة للسرية.',
 faqEyebrow:'أسئلة',faqTitle:'أسئلة تصلنا كثيراً.',
 faq:[['هل التدريب بالعربية؟','نعم. الجلسات والمواد والأمثلة كلها بالعربية، ويمكن إضافة الإنجليزية عند الحاجة.'],['هل يناسب الأعمال الصغيرة؟','نعم. كثير من عملائنا فرق صغيرة. نبني البرنامج على حجمك، لا العكس.'],['حضوري أم عبر الإنترنت؟','كل شيء عبر الإنترنت. نرقمن عملياتك، ونوثّق كل خطوة، ونسجّل نتائج واضحة يمكن إعادة استخدامها.'],['كم يستغرق البرنامج؟','ورشة العمل يوم واحد. برنامج تُكِّي ستة أسابيع.'],['ماذا لو لم نرَ نتائج؟','الأتعاب بعد النتائج. إن لم تكن راضياً عن النتائج، لا تدفع. مضمون.']],
 contactTitle:'جاهز نناقش الفرص؟',contactBody:'أخبرنا عن عملك وما تريد أن يتقنه فريقك. سنخبرك من أين نبدأ.',wa:'تواصل عبر واتساب',
 brandName:'تُكِّي',by:'من مولبيري آند ريد',rights:'جميع الحقوق محفوظة.'
},
en:{
 dir:'ltr',switchTo:'العربية',nav:['How we work','Why Tukki','Pricing','FAQ'],navCta:'Book a call',
 eyebrow:'Growth partners for Iraqi businesses',hero:['Market with confidence.','Grow with clarity.','Be remembered.'],
 heroBody:'We help businesses in Iraq grow with clear marketing and practical training, in Arabic. Three steps: a free discovery call, clear recommendations, then implementation with you.',
 stats:[['50+','businesses served'],['14+','years of experience'],['3','short steps']],
 cta1:'Book a free discovery call',cta2:'How we work',
 howEyebrow:'How we work',howTitle:'Three short steps.',
 steps:[['Free discovery call','We learn about your business and what you want to achieve. No obligation.'],['Clear recommendations','We tell you what to do first, why, and what it will cost.'],['Implementation','We do the work with you, train your team, then measure what changed.']],
 whyEyebrow:'Why Tukki',whyTitle:'Training that makes sense here, and works here.',
 benefits:[['Arabic first','Every session, example and tool is in Arabic.'],['Built on the local market','Examples from the channels and habits people in Iraq actually use.'],['Practical, not theory','Every session ends with a step you apply the same week.'],['For your whole team','From the owner to whoever runs the pages and answers messages.'],['Tools you keep','Templates and worksheets you use long after the training ends.'],['Results you can measure','We agree what we will measure before we start.']],
 priceEyebrow:'Pricing',priceTitle:'What does it cost?',priceBody:'We price around the size of the project or service and what you need. Here is a guide so you know what to expect.',
 prices:[['Discovery call','Free','We learn about your business and see whether Tukki is right for you.'],['Workshop','From IQD 800,000','One training day on a single topic.'],['Tukki programme','From IQD 3,250,000','Six weeks of sessions and follow-up that meet direct needs, with tools and templates for your team.'],['Ongoing support','Custom','Monthly support for your team after the programme. We agree scope and cost before we start.']],
 programEyebrow:'Tukki programme',programTitle:'What does the programme include?',programBody:'We build the programme around what your project needs. These are the services it can include.',programBack:'Back to pricing',
 program:[['Research','We understand the market, customers and opportunities before anything else.'],['Competitor study','What competitors are doing, and where the space is for you.'],['SEO, GEO and AEO analysis','How your business shows up in search engines, AI tools and answer engines.'],['Ideation','Clear ideas built on research, not guesswork.'],['90-day roadmap','A practical plan with clear priorities and dates.'],['Branding','An identity that says who you are and stays in memory.'],['Design system for digital and print','Rules and templates that keep everything you publish consistent.'],['Social media management','Content, posting and engagement on a steady rhythm.'],['Paid advertising','Considered campaigns that reach the right audience.'],['Multiplatform support','A consistent presence across every channel your customers use.'],['Websites','Fast, clear websites that turn visitors into customers.'],['Apps','Apps that serve your business and your customers.'],['CRMs','Systems that organise customer data, follow-up and sales.'],['Reporting and recommendations','Clear numbers and the next steps they point to.']],
 priceNote:'The first session comes with no obligation.',
 quoteTitle:'A word from a client',quote:'Having someone from the outside share tools, systems and opportunities transformed the way we work.',quoteBy:'Client details withheld for confidentiality.',
 faqEyebrow:'FAQ',faqTitle:'Questions we hear often.',
 faq:[['Is the training in Arabic?','Yes. Sessions, materials and examples are all in Arabic. English can be added if you need it.'],['Is it right for small businesses?','Yes. Many of our clients are small teams. We build the programme around your size, not the other way round.'],['In person or online?','Everything is online. We digitise your processes, document every step and record clear outcomes you can reuse.'],['How long does it take?','A workshop is one day. The Tukki programme is six weeks.'],['What if we do not see results?','Fees come after results. If you are not satisfied with the results, you do not pay. Guaranteed.']],
 contactTitle:'Ready to discuss opportunities?',contactBody:'Tell us about your business and what you want your team to master. We will tell you where to start.',wa:'Message us on WhatsApp',
 by:'by Mulberry & Reed',rights:'All rights reserved.'
}};
window.MRres=(id,f)=>(window.__resources&&window.__resources[id])||f;
